# want to redo the archive page
# add content to gallery
# change around styling

baseURL = 'https://blog.iraalulkar.com/'
locale = 'en-us'
title = "Ira's Blog"
theme = 'notrack'

[params]
    author = "Ira Alulkar"
    showTaxonomyLinks = false

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name   = "Writings"
    url    = "/writings/"
    weight = 10

[[menu.main]]
    name   = "Thoughts"
    url    = "/thoughts/"
    weight = 20

[[menu.main]]
    name   = "Categories"
    url    = "/categories/"
    weight = 30

[[menu.main]]
    name   = "Tags"
    url    = "/tags/"
    weight = 40

# gallery code
# ---
# title: 'Gallery'
# date: 2020-06-04T21:53:11+02:00
# menu:
#   main:
#     name: "Gallery"
#     weight: 200
# ---
#
# # What I look like
#
# Here are some pictures of pictures or statues of me, all in the public domain by
# either age or by the use of Creative Commons CC0 license.
#
# {{< gallery-category >}}
#     {{< gallery-photo fn="hugo1.jpg" caption="Clay figure of me" >}}
#     {{< gallery-photo fn="hugo2.jpg" caption="Clay bust of me" >}}
#     {{< gallery-photo fn="hugo4.jpg" caption="Portrait of me as an adult" >}}
#     {{< gallery-photo fn="hugo5.jpg" caption="Portrait of me as a kid" >}}
#     {{< gallery-photo fn="hugo3.jpg" caption="Portrait of me getting screwed over by the Orthodox Calvinists" >}}
# {{< /gallery-category >}}
#
# {{< gallery-modal >}}
# {{< gallery-script >}}


# baseURL = "https://blog.iraalulkar.com"
# locale = "en-us"
# title = "Ira's Blog"
# theme = "notrack"
# pagination.pagerSize = 4  # Posts per page, e.g. in the blog
#
# [params]
# author = "Ira Alulkar"
# # siteHeading = "Hugo Grotius" # defaults to author
# # favicon = "hugo_grotius.png" # The small icon shown in browser tabs
# showTaxonomyLinks = false  # Show e.g. a "Category" button at top of blog page
#
# # You can choose to display a summary of your blog on the home page. Below are
# # the settings relevant for that.
# showBlogLatest = true  # Whether to show it or not
# mainSections = ["blog"]  # Section name of your blog (folder name)
# blogLatestHeading = "Thoughts"  # Heading above blog summary
# nBlogLatest = 4  # Number of blog post in summary
#
# [taxonomies]
# year = "year"
# month = "month"
# tags = "tags"
# categories = "categories"
#
# [permalinks]
#   thoughts = "/thoughts/:year/:month/:slug"
#   writings = "/writings/:year/:month/:slug"
#
# # # [params.social]
# # github = "example"
# # linkedin = "example"
# # email = "example@example.com"
# # mastodon = "example"
# # rss = "yes"  # Value doesn't matter - it will always link to your blog RSS
# # keybase = "example"

# Contact page code
# ---
# title: "Contact"
# date: 2020-06-04T23:03:21+02:00
# menu:
#   main:
#     name: "Contact"
#     weight: 255
# ---
#
# {{< contact-box >}}
#
# To the right you see the `contact-box` shortcode demonstrated and
# below is the `social` shortcode. Use which you like more or make your
# own.
#
# Repudiandae in pariatur voluptatibus inventore alias. Aut quasi non eos earum
# odio maxime quo molestiae. Velit quidem magnam eos odit. Quisquam deleniti
# officia quia. Harum dolorem est sed. Voluptas esse culpa molestias
# exercitationem libero velit sunt hic.
#
# {{< social >}}
